- name: install apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=360000
  become: yes
  with_items:
    - git
    - ruby-full
    - mongodb-clients

- name: BUNDLER | Installing BUNDLER
  become: yes
  command: gem install bundler

#- name: check out the repository on the host
#  git: repo={{ repo_url }} dest={{ proj_path }} accept_hostkey=yes
