- name: get ruby repo
  apt_repository:
    repo: 'ppa:brightbox/ruby-ng'

- name: install apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=360000
  become: yes
  with_items:
    - git
    - ruby2.1
    - mongodb-clients

- name: BUNDLER | Installing BUNDLER
  become: yes
  command: gem install bundler
