- name: NGINX | installing nginx
  apt:
    name: nginx
    update_cache: yes
    #ignore_errors: True
    #register: result
#- debug: var=result

- name: NGINX | create directories for ssl certiifcates
  file:
    path: /etc/nginx/ssl
    state: directory

- name: NGINX | copy TLS key
  copy:
    src: files/nginx.key
    dest: "{{ key_file }}"
    owner: root
    mode: 0600
  notify: restart nginx

- name: NGINX | copy TLS certificate
  copy:
    src: files/nginx.crt
    dest: "{{ cert_file }}"
  notify: restart nginx

- name: NGINX | copy nginx config file
  template:
    src: myDoit_nginx.cfg
    dest: "{{ conf_file }}"
  notify: restart nginx

- name: NGINX | enable configuration
  file:
    dest: /etc/nginx/sites-enabled/default
    src: "{{ conf_file }}"
    state: link
  notify: restart nginx

- name: NGINX | copy index.html
  template:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    mode: 0644