#!/usr/bin/env ansible-playbook
- hosts: all
  tasks:
    - debug: var=ansible_distribution,ansible_env #ansible nginx -m setup -a 'filter=ansible_'

- hosts: db
  become: yes
  vars_files:
    - secrets.yml
  roles:
    - mongodb

- hosts: jenkins
  become: yes
  roles:
    - jenkins

- hosts: nginx
  become: yes
  roles:
    - nginx

- hosts: web
  roles:
    - deploy
