#!/usr/bin/env ansible-playbook
- hosts: all
  gather_facts: True
  tasks:
    - debug: var=ansible_distribution #ansible nginx -m setup -a 'filter=ansible_'

- hosts: nginx
  vars_files:
    - nginx_var.yml
  tasks:
    - include: 'install_nginx.yml'
      become: yes
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

- hosts: web
  tasks:
    - include: 'install_web.yml'
      become: yes

- hosts: db
  tasks:
    - include: 'install_db.yml'
      become: yes
